### PR TITLE
Rutebanken add trace to multiple route sections

### PR DESCRIPTION
**Pull request by lassetyr**
Added functionality to generate all missing routes for a JourneyPattern

screenshot 2016-04-28 15 28 50

screenshot 2016-04-28 15 30 09

### CODE REVIEW

**Comment by brunto** [comment]
Hello, thanks for you request. 

You should know that we are currently working on a new interface for shape edition. This new interface won't edit routes sections anymore, as the shapes will be directly attached to a route. 
If we accept to merge your PR, we would have to delete your modifications, for the next version of Chouette2 (in October), so it is probably not a good idea to merge? Moreover, this new version will also the same feature : to generate all shapes for a line in one click.
Thank you a lot for your contribution.
BTW, could you work on the "develop" branch in the future?

**Comment by seime** [comment]
Hi @brunto , I think we are all looking to improve the functionality. If you will provide a whole new solution in October, we will switch to this instead of maintaining our own copy (we think that all parties working together on a common solution is the only viable path forward, not diverging forks). 

We can pull request to develop next time!

**Comment by brunto** [comment]
Hi, for now the new interface is not developed. We'll keep you tuned soon.

**Comment by brunto** [comment]
Closed due to inactivity.

**Pull request closed without merging**
